name: Run Quality Report

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Run Quality Report
    runs-on: macos-13

    steps:
      - name: Add path globally
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # pin@v4
        with:
          lfs: 'true'

      - name: Build and Test
        run: |
          xcodebuild -scheme SecureStore-Demo test -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" -testPlan UnitTestPlan \
          -enableCodeCoverage YES -resultBundlePath result.xcresult

      - name: Run SonarCloud Scanning
        run: |
          rm '/usr/local/bin/2to3'
          rm '/usr/local/bin/2to3-3.12'
          rm '/usr/local/bin/idle3'
          rm '/usr/local/bin/idle3.12'
          rm '/usr/local/bin/pydoc3'
          rm '/usr/local/bin/pydoc3.12'
          rm '/usr/local/bin/python3'
          rm '/usr/local/bin/python3-config'
          rm '/usr/local/bin/python3.12'
          rm '/usr/local/bin/python3.12-config'
          rm '/usr/local/share/man/man1/python3.1'
          rm '/usr/local/lib/pkgconfig/python3-embed.pc'
          rm '/usr/local/lib/pkgconfig/python3.pc'
          rm '/usr/local/Frameworks/Python.framework/Headers'
          rm '/usr/local/Frameworks/Python.framework/Python'
          rm '/usr/local/Frameworks/Python.framework/Resources'
          rm '/usr/local/Frameworks/Python.framework/Versions/Current'
          rm '/usr/local/bin/2to3-3.11'
          rm '/usr/local/bin/idle3.11'
          rm '/usr/local/bin/pydoc3.11'
          rm '/usr/local/bin/python3.11'
          rm '/usr/local/bin/python3.11-config'

          bash xccov-to-sonarqube-generic.sh result.xcresult/ >Coverage.xml

          brew install sonar-scanner

          sonar-scanner \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.coverageReportPaths="Coverage.xml"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
